#!/usr/bin/env node
// Generate Starlight docs pages from the writing-style-catalog catalog.
//
// Zero-dependency Node ESM port of the former scripts/generate_site_pages.py.
// Reads taxonomy/ and examples/ at the repo root and writes Markdown/MDX into
// the Starlight content tree (default site/src/content/docs/), where Starlight's
// autogenerate sidebar renders it.
//
// Two deliberate differences from the Python generator it replaces:
//   1. Inter-page links are RELATIVE (computed from each page's own slug), so the
//      Pages base segment lives ONLY in site/astro.config.mjs (standard clause
//      14.7). There is no base literal in this file.
//   2. The DiffPair import resolves to site/src/components/DiffPair.astro from the
//      content location site/src/content/docs/examples/diff-pairs/<id>.mdx.
//
// Usage:
//   node scripts/gen-site.mjs                 # write into site/src/content/docs
//   node scripts/gen-site.mjs --out DIR       # write into DIR (must be the site
//                                             # content root or a throwaway dir;
//                                             # source dirs are refused)
//   node scripts/gen-site.mjs --lint          # report source-prose fidelity warnings and exit
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..');
const TAXONOMY = path.join(REPO_ROOT, 'taxonomy');
const EXAMPLES = path.join(REPO_ROOT, 'examples');
const DEFAULT_OUT = path.join(REPO_ROOT, 'site', 'src', 'content', 'docs');
const RECIPES_DIR = path.join(EXAMPLES, 'horizontal-slices');
const GENERATED_SUBDIRS = ['reference', 'examples', 'recipes', 'templates'];

const AXES = ['voice', 'tone', 'style', 'format'];
const AXIS_DIR = { voice: 'voices', tone: 'tones', style: 'styles', format: 'formats' };
const AXIS_LABEL = { voice: 'Voices', tone: 'Tones', style: 'Styles', format: 'Formats' };
const TOPICS = ['async-standups', 'morning-routine', 'service-database-choice', 'roadmap-deprioritization', 'onboarding-a-new-hire', 'thanking-a-mentor', 'daily-rest-practice', 'retirement-send-off', 'team-milestone-celebration'];

const GENERATED_BANNER =
  '<!-- GENERATED by scripts/gen-site.mjs - do not edit by hand. ' +
  'Edit the source under taxonomy/ or examples/ and regenerate. -->';
const GENERATED_BANNER_MDX =
  '{/* GENERATED by scripts/gen-site.mjs - do not edit by hand. ' +
  'Edit the source under taxonomy/ or examples/ and regenerate. */}';

// DiffPair import path from site/src/content/docs/examples/diff-pairs/<id>.mdx
// up to site/src/components/DiffPair.astro (diff-pairs -> examples -> docs ->
// content -> src, then components/). Four levels up.
const DIFF_PAIR_IMPORT = '../../../../components/DiffPair.astro';

// ----------------------------------------------------------------------------
// Frontmatter + YAML-subset parsing (replaces PyYAML)
// ----------------------------------------------------------------------------

// Match the opening/closing frontmatter delimiters. Mirrors the Python
// load_markdown split: first '\n---\n' after the opening closes the block.
const FM_SPLIT = /^---[ \t]*\n([\s\S]*?)\n---[ \t]*\n?([\s\S]*)$/;

function stripQuotes(raw) {
  const s = raw.trim();
  if (s.length >= 2 && s[0] === '"' && s[s.length - 1] === '"') {
    return s.slice(1, -1);
  }
  if (s.length >= 2 && s[0] === "'" && s[s.length - 1] === "'") {
    return s.slice(1, -1).replace(/''/g, "'");
  }
  return s;
}

// Parse a frontmatter block into an object. Handles the YAML subset used by the
// catalog: inline scalars (optionally quoted), literal block scalars (key: |),
// block lists (key: then '- item' lines), and nested maps (only so the parser
// does not mis-read a following top-level key; values are not consumed here).
function parseFrontmatter(fmText) {
  const lines = fmText.split('\n');
  const obj = {};
  const TOP = /^([A-Za-z0-9_][A-Za-z0-9_-]*):(.*)$/;
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (line.trim() === '' || /^\s*#/.test(line)) { i++; continue; }
    const m = line.match(TOP);
    if (!m) { i++; continue; } // indented or non key:value stray line; skip
    const key = m[1];
    const restTrim = m[2].trim();

    if (['|', '|-', '|+', '>', '>-', '>+'].includes(restTrim)) {
      // Literal/folded block scalar: collect more-indented (or blank) lines.
      const block = [];
      i++;
      while (i < lines.length) {
        const l = lines[i];
        if (l.trim() === '') { block.push(''); i++; continue; }
        const indent = l.length - l.trimStart().length;
        if (indent === 0) break;
        block.push(l);
        i++;
      }
      while (block.length && block[block.length - 1] === '') block.pop();
      const indents = block.filter((l) => l.trim() !== '').map((l) => l.length - l.trimStart().length);
      const minIndent = indents.length ? Math.min(...indents) : 0;
      const dedented = block.map((l) => (l === '' ? '' : l.slice(minIndent)));
      if (restTrim.startsWith('>')) {
        // Folded scalar: join consecutive non-blank lines with a space; blank
        // lines become paragraph breaks. Matches PyYAML for prose.
        const parts = [];
        let para = [];
        for (const l of dedented) {
          if (l === '') {
            if (para.length) { parts.push(para.join(' ')); para = []; }
            parts.push('');
          } else {
            para.push(l);
          }
        }
        if (para.length) parts.push(para.join(' '));
        obj[key] = parts.join('\n');
      } else {
        obj[key] = dedented.join('\n');
      }
      continue;
    }

    if (restTrim === '') {
      // Block list or nested map: collect the indented region.
      const block = [];
      i++;
      while (i < lines.length) {
        const l = lines[i];
        if (l.trim() === '') { i++; continue; }
        const indent = l.length - l.trimStart().length;
        if (indent === 0) break;
        block.push(l);
        i++;
      }
      if (block.length && /^-\s+/.test(block[0].trimStart())) {
        // Block sequence. Group lines into items at each '- ' line, then decide
        // scalar list vs list of maps. An item is a map when its content after
        // the dash is a bare 'key: value' pair; quoted scalars never match, so
        // string lists (including quoted strings that contain colons) stay
        // scalar, matching the prior behavior.
        const KV = /^([A-Za-z0-9_][A-Za-z0-9_-]*):\s*(.*)$/;
        const items = [];
        let cur = null;
        for (const l of block) {
          const t = l.trimStart();
          if (/^-\s+/.test(t)) {
            if (cur) items.push(cur);
            cur = { head: t.replace(/^-\s+/, ''), cont: [] };
          } else if (cur && t !== '') {
            cur.cont.push(t);
          }
        }
        if (cur) items.push(cur);

        if (items.length && items.every((it) => KV.test(it.head))) {
          obj[key] = items.map((it) => {
            const map = {};
            for (const line of [it.head, ...it.cont]) {
              const km = line.match(KV);
              if (km) map[km[1]] = stripQuotes(km[2]);
            }
            return map;
          });
        } else {
          obj[key] = items.map((it) => stripQuotes(it.head));
        }
      } else {
        const sub = {};
        for (const l of block) {
          const sm = l.trim().match(TOP);
          if (sm) sub[sm[1]] = stripQuotes(sm[2]);
        }
        obj[key] = sub;
      }
      continue;
    }

    if (restTrim.startsWith('[') && restTrim.endsWith(']')) {
      // Inline (flow) list, e.g. pairs_well_with: [warm, candid].
      const inner = restTrim.slice(1, -1).trim();
      obj[key] = inner === '' ? [] : inner.split(',').map((s) => stripQuotes(s.trim()));
    } else {
      obj[key] = stripQuotes(restTrim);
    }
    i++;
  }
  return obj;
}

// Split a frontmatter markdown string into [frontmatter object, body].
// Normalizes CRLF/CR to LF first (the repo ships CRLF files), matching the
// Python generator so generated output does not depend on line endings.
function loadMarkdown(raw) {
  const text = raw.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const m = text.match(FM_SPLIT);
  if (!m) throw new Error('no frontmatter block found');
  return [parseFrontmatter(m[1]), m[2]];
}

function readText(p) {
  return fs.readFileSync(p, 'utf8');
}

// ----------------------------------------------------------------------------
// Catalog model
// ----------------------------------------------------------------------------

function readEntry(axis, entryDir) {
  const [fm, body] = loadMarkdown(readText(path.join(entryDir, 'ENTRY.md')));
  fm._axis = axis;
  fm._body = body;
  return fm;
}

function loadCatalog() {
  const byId = {};
  const byAxis = {};
  for (const axis of AXES) {
    byAxis[axis] = [];
    const axisPath = path.join(TAXONOMY, AXIS_DIR[axis]);
    const names = fs.readdirSync(axisPath).sort();
    for (const name of names) {
      const entryDir = path.join(axisPath, name);
      if (!fs.statSync(entryDir).isDirectory()) continue;
      const entry = readEntry(axis, entryDir);
      byId[entry.id] = entry;
      byAxis[axis].push(entry);
    }
  }
  return { byId, byAxis };
}

// ----------------------------------------------------------------------------
// Slugs + relative links (no base literal; clause 14.7)
// ----------------------------------------------------------------------------

// Route slug (no leading/trailing slash) for an entry's reference page.
function refSlug(entry) {
  return `reference/${AXIS_DIR[entry._axis]}/${entry.id}`;
}

// Relative URL (with trailing slash) from one page slug to another. Each page
// renders to a directory (<slug>/index.html), so the link resolves against the
// current page's directory URL, which already includes the configured base.
function relUrl(fromSlug, toSlug) {
  const from = fromSlug ? fromSlug.split('/') : [];
  const to = toSlug ? toSlug.split('/') : [];
  let common = 0;
  while (common < from.length && common < to.length && from[common] === to[common]) common++;
  const ups = from.length - common;
  const downs = to.slice(common);
  const rel = '../'.repeat(ups) + downs.map((s) => `${s}/`).join('');
  return rel === '' ? './' : rel;
}

// Markdown link to an entry by id from a given page, using its display name.
// Falls back to a code span if the id is unknown.
function entryLink(catalog, fromSlug, entryId) {
  const entry = catalog.byId[entryId];
  if (!entry) return `\`${entryId}\``;
  return `[${entry.name}](${relUrl(fromSlug, refSlug(entry))})`;
}

// ----------------------------------------------------------------------------
// Examples + diff-pairs
// ----------------------------------------------------------------------------

// Map topic-slug -> { body, topicLabel } for an entry's vertical slices.
function examplesForEntry(entryId) {
  const out = {};
  for (const topic of TOPICS) {
    const topicDir = path.join(EXAMPLES, 'vertical-slices', topic);
    if (!fs.existsSync(topicDir)) continue;
    const mds = fs.readdirSync(topicDir).filter((f) => f.endsWith('.md')).sort();
    for (const md of mds) {
      const [fm, body] = loadMarkdown(readText(path.join(topicDir, md)));
      if (fm.entry_id === entryId) {
        out[topic] = { body, topicLabel: fm.topic_label || topic };
        break;
      }
    }
  }
  return out;
}

// Diff-pair bodies have three top-level boundary headers, in order:
// "## What to notice", "## A: `id`", "## B: `id`". Passages may contain their
// own nested ## headers, so split ONLY on the boundary headers (matched by text).
const H2 = /^##\s+(.*?)\s*$/gm;

function sectionKey(header) {
  const h = header.toLowerCase();
  if (h.startsWith('what to notice')) return 'what_to_notice';
  if (h.startsWith('a:')) return 'passage_a';
  if (h.startsWith('b:')) return 'passage_b';
  return null;
}

function parseDiffPair(raw) {
  const [fm, body] = loadMarkdown(raw);
  const boundaries = [];
  let mt;
  H2.lastIndex = 0;
  while ((mt = H2.exec(body)) !== null) {
    if (sectionKey(mt[1]) !== null) {
      boundaries.push({ key: sectionKey(mt[1]), start: mt.index, end: mt.index + mt[0].length });
    }
  }
  const sections = {};
  for (let i = 0; i < boundaries.length; i++) {
    const b = boundaries[i];
    const start = b.end;
    const end = i + 1 < boundaries.length ? boundaries[i + 1].start : body.length;
    let text = body.slice(start, end).trim();
    text = text.replace(/\n+---\s*$/, '').trim();
    sections[b.key] = text;
  }
  return {
    entry_a: fm.entry_a,
    entry_b: fm.entry_b,
    axis_varied: fm.axis_varied,
    topic_label: fm.topic_label || '',
    diff_pair_id: fm.diff_pair_id || '',
    what_to_notice: sections.what_to_notice || '',
    passage_a: sections.passage_a || '',
    passage_b: sections.passage_b || '',
  };
}

function walkMarkdown(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const st = fs.statSync(full);
    if (st.isDirectory()) out.push(...walkMarkdown(full));
    else if (name.endsWith('.md')) out.push(full);
  }
  return out;
}

function loadDiffPairs() {
  const base = path.join(EXAMPLES, 'diff-pairs');
  // Sort by repo-relative POSIX path to match the Python rglob + sorted order.
  const files = walkMarkdown(base)
    .filter((f) => path.basename(f) !== 'README.md')
    .sort((a, b) => {
      const ra = path.relative(base, a).split(path.sep).join('/');
      const rb = path.relative(base, b).split(path.sep).join('/');
      return ra < rb ? -1 : ra > rb ? 1 : 0;
    });
  return files.map((f) => parseDiffPair(readText(f)));
}

function diffPairsForEntry(pairs, entryId) {
  return pairs.filter((p) => p.entry_a === entryId || p.entry_b === entryId);
}

// ----------------------------------------------------------------------------
// Rendering helpers
// ----------------------------------------------------------------------------

// Safe single-line YAML scalar for a frontmatter title/description.
function yamlTitle(text) {
  return `"${String(text == null ? '' : text).replace(/"/g, "'")}"`;
}

// Source-prose defect patterns that would render verbatim on the live site.
const FIDELITY_PATTERNS = [
  [/\s\./, 'space before period (orphan period, e.g. stray em-dash sweep)'],
  [/(?<!\.)\.\.(?!\.)/, 'doubled period'],
  [/,,/, 'doubled comma'],
  [/\bTODO\b|\bTKTK\b/, 'unfinished marker'],
];

function fidelityWarnings(text) {
  const hits = [];
  for (const [rx, msg] of FIDELITY_PATTERNS) {
    if (rx.test(text)) hits.push(msg);
  }
  return hits;
}

// Escape `<` and `{` outside code fences/spans so prose embeds safely in MDX.
const FENCE_OR_SPAN = /(^```[\s\S]*?^```|`[^`\n]*`)/gm;

function escapeChunk(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/\{/g, '&lbrace;');
}

function mdxEscapeProse(text) {
  const parts = [];
  let last = 0;
  let m;
  FENCE_OR_SPAN.lastIndex = 0;
  while ((m = FENCE_OR_SPAN.exec(text)) !== null) {
    parts.push(escapeChunk(text.slice(last, m.index)));
    parts.push(m[0]);
    last = m.index + m[0].length;
    if (m[0].length === 0) FENCE_OR_SPAN.lastIndex++; // guard against zero-width
  }
  parts.push(escapeChunk(text.slice(last)));
  return parts.join('');
}

function xrefBlock(catalog, fromSlug, entry, field, heading) {
  const ids = entry[field] || [];
  if (!ids.length) return '';
  const links = ids.map((id) => entryLink(catalog, fromSlug, id)).join(', ');
  return `### ${heading}\n\n${links}\n\n`;
}

function joinPage(lines) {
  return `${lines.join('\n').replace(/\s+$/, '')}\n`;
}

// Render the ADR 0009 pedagogical fields (tells / anti_patterns / failure_modes)
// as page sections. Frontmatter is the single source of truth; entries that have
// not been backfilled yet simply contribute nothing.
function pedagogySections(entry) {
  const out = [];
  const tells = Array.isArray(entry.tells) ? entry.tells : [];
  if (tells.length) {
    out.push('## Tells', '');
    for (const t of tells) out.push(`- ${mdxEscapeProse(String(t))}`);
    out.push('');
  }
  const anti = Array.isArray(entry.anti_patterns) ? entry.anti_patterns : [];
  if (anti.length) {
    out.push('## Anti-patterns', '');
    for (const a of anti) {
      if (a && a.pattern) {
        out.push(`- **${mdxEscapeProse(String(a.pattern))}** - ${mdxEscapeProse(String(a.why || ''))}`);
      }
    }
    out.push('');
  }
  const fm = Array.isArray(entry.failure_modes) ? entry.failure_modes : [];
  if (fm.length) {
    out.push('## Failure modes', '');
    for (const f of fm) {
      if (f && f.mode) {
        out.push(`- **${mdxEscapeProse(String(f.mode))}** - ${mdxEscapeProse(String(f.mitigation || ''))}`);
      }
    }
    out.push('');
  }
  return out;
}

function renderEntryPage(catalog, pairs, entry) {
  const axis = entry._axis;
  const fromSlug = refSlug(entry);
  const out = [];
  out.push('---');
  out.push(`title: ${yamlTitle(entry.name)}`);
  out.push(`description: ${yamlTitle(entry.one_liner || '')}`);
  out.push('editUrl: false');
  out.push('---');
  out.push('');
  out.push(GENERATED_BANNER_MDX);
  out.push('');
  out.push("import { Tabs, TabItem } from '@astrojs/starlight/components';");
  out.push('');
  out.push(`> ${entry.one_liner || ''}`);
  out.push('');
  out.push((entry._body || '').trim());
  out.push('');

  for (const line of pedagogySections(entry)) out.push(line);

  const phrasing = (entry.llm_instruction_phrasing || '').trim();
  if (phrasing) {
    out.push('## Instruction');
    out.push('');
    out.push('```text');
    out.push(phrasing);
    out.push('```');
    out.push('');
  }

  if (axis === 'format' && entry.canonical_template) {
    out.push('## Template');
    out.push('');
    out.push(`See the [${entry.name} template](${relUrl(fromSlug, `templates/${entry.id}`)}).`);
    out.push('');
  }

  let xref = '';
  xref += xrefBlock(catalog, fromSlug, entry, 'pairs_well_with', 'Pairs well with');
  xref += xrefBlock(catalog, fromSlug, entry, 'avoid_with', 'Avoid with');
  xref += xrefBlock(catalog, fromSlug, entry, 'confusable_with', 'Often confused with');
  if (xref) {
    out.push('## Related');
    out.push('');
    out.push(xref.replace(/\s+$/, ''));
    out.push('');
  }

  const examples = examplesForEntry(entry.id);
  if (Object.keys(examples).length) {
    out.push('## Examples');
    out.push('');
    out.push('<Tabs>');
    for (const topic of TOPICS) {
      const rec = examples[topic];
      if (!rec) continue;
      out.push(`<TabItem label="${rec.topicLabel}">`);
      out.push('');
      out.push(mdxEscapeProse(rec.body.trim()));
      out.push('');
      out.push('</TabItem>');
    }
    out.push('</Tabs>');
    out.push('');
  }

  const appears = diffPairsForEntry(pairs, entry.id);
  if (appears.length) {
    out.push('## Appears in diff-pairs');
    out.push('');
    for (const p of appears) {
      const other = p.entry_a === entry.id ? p.entry_b : p.entry_a;
      out.push(
        `- [${entry.id} vs ${other}]` +
          `(${relUrl(fromSlug, `examples/diff-pairs/${p.diff_pair_id}`)}) ` +
          `(varies ${p.axis_varied})`
      );
    }
    out.push('');
  }

  return joinPage(out);
}

function renderDiffPairPage(catalog, dp) {
  const fromSlug = `examples/diff-pairs/${dp.diff_pair_id}`;
  const aLink = entryLink(catalog, fromSlug, dp.entry_a);
  const bLink = entryLink(catalog, fromSlug, dp.entry_b);
  const ea = dp.entry_a;
  const eb = dp.entry_b;
  const out = [
    '---',
    `title: ${yamlTitle(`${ea} vs ${eb}`)}`,
    `description: ${yamlTitle(dp.topic_label)}`,
    'editUrl: false',
    '---',
    '',
    GENERATED_BANNER_MDX,
    '',
    `import DiffPair from '${DIFF_PAIR_IMPORT}';`,
    '',
    `**Topic:** ${dp.topic_label}  `,
    `**Axis varied:** ${dp.axis_varied}  `,
    `**A:** ${aLink}  **B:** ${bLink}`,
    '',
    '## What to notice',
    '',
    mdxEscapeProse(dp.what_to_notice),
    '',
    `<DiffPair labelA="A: ${ea}" labelB="B: ${eb}">`,
    '<div slot="a">',
    '',
    mdxEscapeProse(dp.passage_a),
    '',
    '</div>',
    '<div slot="b">',
    '',
    mdxEscapeProse(dp.passage_b),
    '',
    '</div>',
    '</DiffPair>',
    '',
  ];
  return joinPage(out);
}

function renderTemplatePage(fmt) {
  const fromSlug = `templates/${fmt.id}`;
  const template = (fmt.canonical_template || '').replace(/\s+$/, '');
  const out = [
    '---',
    `title: ${yamlTitle(`${fmt.name} template`)}`,
    `description: ${yamlTitle(`Canonical template for the ${fmt.name} format.`)}`,
    'editUrl: false',
    '---',
    '',
    GENERATED_BANNER,
    '',
    `Canonical template for the [${fmt.name}](${relUrl(fromSlug, refSlug(fmt))}) format.`,
    '',
    '```markdown',
    template,
    '```',
    '',
  ];
  return joinPage(out);
}

// Replace `id` backtick tokens in a recipe README with entry links.
function linkEntryNamesInTable(catalog, fromSlug, text) {
  return text.replace(/`([a-z][a-z0-9-]*)`/g, (full, token) =>
    catalog.byId[token] ? entryLink(catalog, fromSlug, token) : full
  );
}

// Convert relative links to local .md files into plain text (their targets are
// not generated into the site, so the links would 404). Leaves http(s) and
// site-absolute links intact.
function stripLocalMdLinks(text) {
  return text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (full, label, target) => {
    if (target.startsWith('http') || target.startsWith('/')) return full;
    if (target.split('#')[0].endsWith('.md')) return label;
    return full;
  });
}

function renderRecipePage(catalog, recipeSlug) {
  const readme = readText(path.join(RECIPES_DIR, recipeSlug, 'README.md')).replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const lines = readme.split('\n');
  const heading = lines.length ? lines[0].replace(/^#\s*/, '').replace(/^#+/, '').trim() : recipeSlug;
  let body = lines.slice(1).join('\n').trim();
  body = stripLocalMdLinks(body);
  body = linkEntryNamesInTable(catalog, `recipes/${recipeSlug}`, body);
  const out = [
    '---',
    `title: ${yamlTitle(heading)}`,
    'editUrl: false',
    '---',
    '',
    GENERATED_BANNER,
    '',
    body,
    '',
  ];
  return joinPage(out);
}

function listRecipes() {
  if (!fs.existsSync(RECIPES_DIR)) return [];
  return fs
    .readdirSync(RECIPES_DIR)
    .filter((d) => {
      const full = path.join(RECIPES_DIR, d);
      return fs.statSync(full).isDirectory() && fs.existsSync(path.join(full, 'README.md'));
    })
    .sort();
}

function page(title, description, body) {
  const out = [
    '---',
    `title: ${yamlTitle(title)}`,
    `description: ${yamlTitle(description)}`,
    'editUrl: false',
    '---',
    '',
    GENERATED_BANNER,
    '',
    body.trim(),
    '',
  ];
  return joinPage(out);
}

function renderReferenceIndex(catalog) {
  const fromSlug = 'reference';
  const parts = [];
  for (const axis of AXES) {
    parts.push(`## ${AXIS_LABEL[axis]}`);
    parts.push('');
    for (const e of catalog.byAxis[axis]) {
      parts.push(`- [${e.name}](${relUrl(fromSlug, refSlug(e))}) - ${e.one_liner || ''}`);
    }
    parts.push('');
  }
  return page('Reference', 'Every entry across the four axes.', parts.join('\n'));
}

function renderDiffPairIndex(pairs) {
  const fromSlug = 'examples/diff-pairs';
  const byAxis = {};
  for (const p of pairs) (byAxis[p.axis_varied] = byAxis[p.axis_varied] || []).push(p);
  const parts = [];
  for (const axis of Object.keys(byAxis).sort()) {
    parts.push(`## Varying ${axis}`);
    parts.push('');
    for (const p of byAxis[axis]) {
      parts.push(
        `- [${p.entry_a} vs ${p.entry_b}]` +
          `(${relUrl(fromSlug, `examples/diff-pairs/${p.diff_pair_id}`)}) - ${p.topic_label}`
      );
    }
    parts.push('');
  }
  return page('Diff-pairs', 'Side-by-side single-axis contrasts.', parts.join('\n'));
}

function renderRecipeIndex() {
  const fromSlug = 'recipes';
  const parts = [];
  for (const slug of listRecipes()) {
    parts.push(`- [${slug}](${relUrl(fromSlug, `recipes/${slug}`)})`);
  }
  return page('Recipes', 'Curated four-axis compositions.', parts.join('\n'));
}

function renderTemplateIndex(catalog) {
  const fromSlug = 'templates';
  const parts = [];
  for (const e of catalog.byAxis.format) {
    if (e.canonical_template) parts.push(`- [${e.name}](${relUrl(fromSlug, `templates/${e.id}`)})`);
  }
  return page('Templates', 'Canonical format templates.', parts.join('\n'));
}

function renderExamplesTopicIndex(topic) {
  const body =
    'Vertical-slice examples for this topic, one per entry. ' +
    "Each is also embedded on its entry's reference page.\n";
  return page(topic, `Examples for the ${topic} anchor topic.`, body);
}

// ----------------------------------------------------------------------------
// Generation
// ----------------------------------------------------------------------------

function write(outRoot, rel, content) {
  const p = path.join(outRoot, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content, 'utf8');
}

// Guard the destructive cleanup below. The output root must be a throwaway or
// the site content directory, never a repo source tree: without this,
// `gen-site.mjs --out .` from the repo root would clear outRoot/examples, which
// is the real examples/ source tree (data loss). Refuses outRoot when it is, is
// an ancestor of, or sits inside a protected source directory, or when clearing
// any generated subtree would hit one.
function assertSafeOutRoot(outRoot) {
  const abs = path.resolve(outRoot);
  const root = path.resolve(REPO_ROOT);
  const sourceDirs = ['taxonomy', 'examples', 'docs', 'schemas', 'scripts', 'tools', 'tests', 'skills'].map((d) =>
    path.join(root, d)
  );
  const insideOrEqual = (p, r) => p === r || p.startsWith(r + path.sep);
  const cleared = GENERATED_SUBDIRS.map((s) => path.join(abs, s));
  const unsafe =
    abs === root ||
    root.startsWith(abs + path.sep) ||
    sourceDirs.some((r) => insideOrEqual(abs, r)) ||
    cleared.some((c) => sourceDirs.some((r) => insideOrEqual(c, r)));
  if (unsafe) {
    throw new Error(
      `gen-site: refusing to generate into '${abs}'. It is, contains, or sits inside a protected ` +
        'source directory, so clearing the generated subtrees could delete real source. Use the ' +
        'default output (site/src/content/docs) or a throwaway directory.'
    );
  }
}

function generate(outRoot) {
  assertSafeOutRoot(outRoot);
  const catalog = loadCatalog();
  const pairs = loadDiffPairs();
  let n = 0;

  // Clear previously generated subtrees first, so an in-place rebuild (the
  // catalog is gitignored and not drift-guarded) cannot leave a stale page
  // whose source was removed. Only generated dirs are cleared; the hand-authored
  // narrative under the same content root is untouched.
  for (const sub of GENERATED_SUBDIRS) {
    fs.rmSync(path.join(outRoot, sub), { recursive: true, force: true });
  }

  // Entry pages (.mdx because they import components / use <Tabs>).
  for (const axis of AXES) {
    for (const entry of catalog.byAxis[axis]) {
      write(outRoot, `reference/${AXIS_DIR[axis]}/${entry.id}.mdx`, renderEntryPage(catalog, pairs, entry));
      n += 1;
    }
  }
  write(outRoot, 'reference/index.md', renderReferenceIndex(catalog));

  // Diff-pair pages (.mdx, import DiffPair).
  for (const dp of pairs) {
    write(outRoot, `examples/diff-pairs/${dp.diff_pair_id}.mdx`, renderDiffPairPage(catalog, dp));
    n += 1;
  }
  write(outRoot, 'examples/diff-pairs/index.md', renderDiffPairIndex(pairs));

  // Example topic index pages.
  for (const topic of TOPICS) {
    write(outRoot, `examples/${topic}/index.md`, renderExamplesTopicIndex(topic));
  }

  // Recipes.
  for (const slug of listRecipes()) {
    write(outRoot, `recipes/${slug}.md`, renderRecipePage(catalog, slug));
    n += 1;
  }
  write(outRoot, 'recipes/index.md', renderRecipeIndex());

  // Templates.
  for (const e of catalog.byAxis.format) {
    if (e.canonical_template) {
      write(outRoot, `templates/${e.id}.md`, renderTemplatePage(e));
      n += 1;
    }
  }
  write(outRoot, 'templates/index.md', renderTemplateIndex(catalog));

  return n;
}

function runLint() {
  const catalog = loadCatalog();
  let total = 0;
  for (const axis of AXES) {
    for (const e of catalog.byAxis[axis]) {
      for (const w of fidelityWarnings(e._body || '')) {
        console.log(`taxonomy/${AXIS_DIR[axis]}/${e.id}/ENTRY.md: ${w}`);
        total += 1;
      }
    }
  }
  for (const md of walkMarkdown(path.join(EXAMPLES, 'vertical-slices'))) {
    const [, body] = loadMarkdown(readText(md));
    for (const w of fidelityWarnings(body)) {
      console.log(`${path.relative(REPO_ROOT, md).split(path.sep).join('/')}: ${w}`);
      total += 1;
    }
  }
  console.log(`[lint] ${total} fidelity warning(s)`);
}

function main() {
  const args = process.argv.slice(2);
  if (args.includes('--lint')) {
    runLint();
    return;
  }
  let outRoot = DEFAULT_OUT;
  const outIdx = args.indexOf('--out');
  if (outIdx !== -1 && args[outIdx + 1]) outRoot = path.resolve(args[outIdx + 1]);
  const count = generate(outRoot);
  console.log(`[OK] generated ${count} catalog pages into ${outRoot}`);
}

export {
  relUrl,
  refSlug,
  entryLink,
  parseFrontmatter,
  loadMarkdown,
  mdxEscapeProse,
  parseDiffPair,
  loadCatalog,
  loadDiffPairs,
  assertSafeOutRoot,
  generate,
};

// Run only when executed directly (node scripts/gen-site.mjs), not when imported
// by a test. process.argv[1] is the invoked script path.
if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  main();
}
