#!/usr/bin/env python3
"""Generate Starlight docs pages from the writing-style-library catalog.

Reads taxonomy/ and examples/ (with PyYAML, NOT the repo's hand-rolled parser)
and writes committed Markdown/MDX into docs/ where Starlight's autogenerate
sidebar renders it. Emits Starlight-correct slug links in-generator; there is
NO post-build link rewriter (see ADR 0011 and the design spec section 5.5).

Usage:
    python scripts/generate_site_pages.py            # write into docs/
    python scripts/generate_site_pages.py --out DIR  # write into DIR (used by the freshness check)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
TAXONOMY = REPO_ROOT / "taxonomy"
EXAMPLES = REPO_ROOT / "examples"
DOCS = REPO_ROOT / "docs"
RECIPES_DIR = EXAMPLES / "horizontal-slices"

AXES = ["voice", "tone", "style", "format"]
AXIS_DIR = {"voice": "voices", "tone": "tones", "style": "styles", "format": "formats"}
TOPICS = ["async-standups", "morning-routine", "service-database-choice"]

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/generate_site_pages.py - do not edit by hand. "
    "Edit the source under taxonomy/ or examples/ and regenerate. -->"
)

GENERATED_BANNER_MDX = (
    "{/* GENERATED by scripts/generate_site_pages.py - do not edit by hand. "
    "Edit the source under taxonomy/ or examples/ and regenerate. */}"
)

_FM_SPLIT = re.compile(r"(?ms)\A---[ \t]*\n(.*?)\n---[ \t]*\n?(.*)\Z")


def load_markdown(raw: str) -> tuple[dict, str]:
    """Split a frontmatter markdown string into (frontmatter dict, body).

    Normalizes CRLF/CR to LF first so the result does not depend on how the
    caller obtained the string (the repo ships CRLF files).
    """
    raw = raw.replace("\r\n", "\n").replace("\r", "\n")
    m = _FM_SPLIT.match(raw)
    if not m:
        raise ValueError("no frontmatter block found")
    fm = yaml.safe_load(m.group(1)) or {}
    return fm, m.group(2)


def read_entry(axis: str, entry_dir: Path) -> dict:
    fm, body = load_markdown((entry_dir / "ENTRY.md").read_text(encoding="utf-8"))
    fm["_axis"] = axis
    fm["_body"] = body
    return fm


BASE = "/writing-style-library"


def entry_url(axis: str, entry_id: str) -> str:
    """Starlight slug URL for an entry's reference page (trailing slash)."""
    return f"{BASE}/reference/{AXIS_DIR[axis]}/{entry_id}/"


def entry_link(catalog: dict, entry_id: str) -> str:
    """Markdown link to an entry by id, using its display name. Falls back to the id."""
    entry = catalog["by_id"].get(entry_id)
    if not entry:
        return f"`{entry_id}`"
    return f"[{entry['name']}]({entry_url(entry['_axis'], entry_id)})"


def load_catalog() -> dict:
    by_id: dict[str, dict] = {}
    by_axis: dict[str, list[dict]] = {a: [] for a in AXES}
    for axis in AXES:
        axis_path = TAXONOMY / AXIS_DIR[axis]
        for entry_dir in sorted(axis_path.iterdir()):
            if not entry_dir.is_dir():
                continue
            entry = read_entry(axis, entry_dir)
            by_id[entry["id"]] = entry
            by_axis[axis].append(entry)
    return {"by_id": by_id, "by_axis": by_axis}


def examples_for_entry(entry_id: str) -> dict:
    """Map topic-slug -> {body, topic_label} for an entry's vertical slices."""
    out: dict[str, dict] = {}
    for topic in TOPICS:
        topic_dir = EXAMPLES / "vertical-slices" / topic
        if not topic_dir.exists():
            continue
        for md in sorted(topic_dir.glob("*.md")):
            fm, body = load_markdown(md.read_text(encoding="utf-8"))
            if fm.get("entry_id") == entry_id:
                out[topic] = {"body": body, "topic_label": fm.get("topic_label", topic)}
                break
    return out


# Diff-pair bodies have three top-level boundary headers, in this order:
# "## What to notice", "## A: `id`", "## B: `id`". Passages may contain their
# own nested ## headers, so split ONLY on the boundary headers (matched by
# header text), not on every ## line.
_H2 = re.compile(r"(?m)^##\s+(.*?)\s*$")


def _section_key(header: str) -> str | None:
    h = header.lower()
    if h.startswith("what to notice"):
        return "what_to_notice"
    if h.startswith("a:"):
        return "passage_a"
    if h.startswith("b:"):
        return "passage_b"
    return None


def parse_diff_pair(raw: str) -> dict:
    fm, body = load_markdown(raw)
    # Keep only the top-level boundary headers as split points.
    boundaries = [m for m in _H2.finditer(body) if _section_key(m.group(1)) is not None]
    sections: dict[str, str] = {}
    for i, mt in enumerate(boundaries):
        key = _section_key(mt.group(1))
        start = mt.end()
        end = boundaries[i + 1].start() if i + 1 < len(boundaries) else len(body)
        text = body[start:end]
        # Drop a trailing horizontal rule separator and surrounding whitespace.
        text = re.sub(r"\n+---\s*$", "", text.strip()).strip()
        sections[key] = text
    return {
        "entry_a": fm.get("entry_a"),
        "entry_b": fm.get("entry_b"),
        "axis_varied": fm.get("axis_varied"),
        "topic_label": fm.get("topic_label", ""),
        "diff_pair_id": fm.get("diff_pair_id", ""),
        "what_to_notice": sections.get("what_to_notice", ""),
        "passage_a": sections.get("passage_a", ""),
        "passage_b": sections.get("passage_b", ""),
    }


def load_diff_pairs() -> list[dict]:
    out = []
    base = EXAMPLES / "diff-pairs"
    if not base.exists():
        return out
    for md in sorted(base.rglob("*.md")):
        if md.name == "README.md":
            continue
        out.append(parse_diff_pair(md.read_text(encoding="utf-8")))
    return out


def diff_pairs_for_entry(pairs: list[dict], entry_id: str) -> list[dict]:
    return [p for p in pairs if entry_id in (p["entry_a"], p["entry_b"])]


def _yaml_title(text: str) -> str:
    """Safe single-line YAML scalar for a frontmatter title/description."""
    return '"' + text.replace('"', "'") + '"'


# Source-prose defect patterns that would render verbatim on the live site.
_FIDELITY_PATTERNS = [
    (re.compile(r"\s\."), "space before period (orphan period, e.g. stray em-dash sweep)"),
    (re.compile(r"\.\.(?!\.)"), "doubled period"),
    (re.compile(r",,"), "doubled comma"),
    (re.compile(r"\bTODO\b|\bTKTK\b"), "unfinished marker"),
]


def fidelity_warnings(text: str) -> list[str]:
    hits = []
    for rx, msg in _FIDELITY_PATTERNS:
        if rx.search(text):
            hits.append(msg)
    return hits


# Escape MDX-significant characters in markdown prose that will be embedded
# inside an .mdx page (e.g. an example body inside <TabItem>). Only `<` and `{`
# trigger JSX parsing. We must NOT escape inside fenced code blocks or inline
# code spans, where these characters are legitimate code. Returns MDX-safe text.
_FENCE_OR_SPAN = re.compile(r"(?ms)(^```.*?^```|`[^`\n]*`)")


def mdx_escape_prose(text: str) -> str:
    """Escape `<` and `{` outside code fences/spans so prose embeds safely in MDX."""
    parts = []
    last = 0
    for m in _FENCE_OR_SPAN.finditer(text):
        # Escape the prose chunk before this code region.
        chunk = text[last:m.start()]
        parts.append(chunk.replace("&", "&amp;").replace("<", "&lt;").replace("{", "&lbrace;"))
        # Emit the code region verbatim.
        parts.append(m.group(0))
        last = m.end()
    tail = text[last:]
    parts.append(tail.replace("&", "&amp;").replace("<", "&lt;").replace("{", "&lbrace;"))
    return "".join(parts)


def _xref_block(catalog: dict, entry: dict, field: str, heading: str) -> str:
    ids = entry.get(field) or []
    if not ids:
        return ""
    links = ", ".join(entry_link(catalog, i) for i in ids)
    return f"### {heading}\n\n{links}\n\n"


def render_entry_page(catalog: dict, pairs: list[dict], entry: dict) -> str:
    axis = entry["_axis"]
    out = []
    out.append("---")
    out.append(f"title: {_yaml_title(entry['name'])}")
    out.append(f"description: {_yaml_title(entry.get('one_liner', ''))}")
    out.append("---")
    out.append("")
    out.append(GENERATED_BANNER_MDX)
    out.append("")
    out.append("import { Tabs, TabItem } from '@astrojs/starlight/components';")
    out.append("")
    out.append(f"> {entry.get('one_liner', '')}")
    out.append("")
    out.append(entry.get("_body", "").strip())
    out.append("")

    phrasing = entry.get("llm_instruction_phrasing", "").strip()
    if phrasing:
        out.append("## Instruction")
        out.append("")
        out.append("```text")
        out.append(phrasing)
        out.append("```")
        out.append("")

    if axis == "format" and entry.get("canonical_template"):
        out.append("## Template")
        out.append("")
        out.append(f"See the [{entry['name']} template]({BASE}/templates/{entry['id']}/).")
        out.append("")

    xref = ""
    xref += _xref_block(catalog, entry, "pairs_well_with", "Pairs well with")
    xref += _xref_block(catalog, entry, "avoid_with", "Avoid with")
    xref += _xref_block(catalog, entry, "confusable_with", "Often confused with")
    if xref:
        out.append("## Related")
        out.append("")
        out.append(xref.rstrip())
        out.append("")

    examples = examples_for_entry(entry["id"])
    if examples:
        out.append("## Examples")
        out.append("")
        out.append("<Tabs>")
        for topic in TOPICS:
            rec = examples.get(topic)
            if not rec:
                continue
            out.append(f'<TabItem label="{rec["topic_label"]}">')
            out.append("")
            out.append(mdx_escape_prose(rec["body"].strip()))
            out.append("")
            out.append("</TabItem>")
        out.append("</Tabs>")
        out.append("")

    appears = diff_pairs_for_entry(pairs, entry["id"])
    if appears:
        out.append("## Appears in diff-pairs")
        out.append("")
        for p in appears:
            other = p["entry_b"] if p["entry_a"] == entry["id"] else p["entry_a"]
            out.append(
                f"- [{entry['id']} vs {other}]"
                f"({BASE}/examples/diff-pairs/{p['diff_pair_id']}/) "
                f"(varies {p['axis_varied']})"
            )
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def render_diff_pair_page(catalog: dict, dp: dict) -> str:
    a_link = entry_link(catalog, dp["entry_a"])
    b_link = entry_link(catalog, dp["entry_b"])
    ea = dp["entry_a"]
    eb = dp["entry_b"]
    title = f"{ea} vs {eb}"
    out = [
        "---",
        f"title: {_yaml_title(title)}",
        f"description: {_yaml_title(dp['topic_label'])}",
        "---",
        "",
        GENERATED_BANNER_MDX,
        "",
        "import DiffPair from '../../../src/components/DiffPair.astro';",
        "",
        f"**Topic:** {dp['topic_label']}  ",
        f"**Axis varied:** {dp['axis_varied']}  ",
        f"**A:** {a_link}  **B:** {b_link}",
        "",
        "## What to notice",
        "",
        mdx_escape_prose(dp["what_to_notice"]),
        "",
        f'<DiffPair labelA="A: {ea}" labelB="B: {eb}">',
        '<div slot="a">',
        "",
        mdx_escape_prose(dp["passage_a"]),
        "",
        "</div>",
        '<div slot="b">',
        "",
        mdx_escape_prose(dp["passage_b"]),
        "",
        "</div>",
        "</DiffPair>",
        "",
    ]
    return "\n".join(out).rstrip() + "\n"


def render_template_page(fmt: dict) -> str:
    template = (fmt.get("canonical_template") or "").rstrip()
    out = [
        "---",
        f"title: {_yaml_title(fmt['name'] + ' template')}",
        f"description: {_yaml_title('Canonical template for the ' + fmt['name'] + ' format.')}",
        "---",
        "",
        GENERATED_BANNER,
        "",
        f"Canonical template for the [{fmt['name']}]({entry_url('format', fmt['id'])}) format.",
        "",
        "```markdown",
        template,
        "```",
        "",
    ]
    return "\n".join(out).rstrip() + "\n"


def _link_entry_names_in_table(catalog: dict, text: str) -> str:
    """Replace `id` backtick tokens in a recipe README with entry links."""
    def repl(m):
        token = m.group(1)
        return entry_link(catalog, token) if token in catalog["by_id"] else m.group(0)
    return re.sub(r"`([a-z][a-z0-9-]*)`", repl, text)


def render_recipe_page(catalog: dict, recipe_slug: str) -> str:
    readme = (RECIPES_DIR / recipe_slug / "README.md").read_text(encoding="utf-8")
    lines = readme.splitlines()
    heading = lines[0].lstrip("# ").strip() if lines else recipe_slug
    body = "\n".join(lines[1:]).strip()
    body = _link_entry_names_in_table(catalog, body)
    out = [
        "---",
        f"title: {_yaml_title(heading)}",
        "---",
        "",
        GENERATED_BANNER,
        "",
        body,
        "",
    ]
    return "\n".join(out).rstrip() + "\n"


def list_recipes() -> list[str]:
    if not RECIPES_DIR.exists():
        return []
    return sorted(d.name for d in RECIPES_DIR.iterdir() if d.is_dir() and (d / "README.md").exists())


AXIS_LABEL = {"voice": "Voices", "tone": "Tones", "style": "Styles", "format": "Formats"}


def _page(title: str, description: str, body: str) -> str:
    out = [
        "---",
        f"title: {_yaml_title(title)}",
        f"description: {_yaml_title(description)}",
        "---",
        "",
        GENERATED_BANNER,
        "",
        body.strip(),
        "",
    ]
    return "\n".join(out).rstrip() + "\n"


def render_reference_index(catalog: dict) -> str:
    parts = []
    for axis in AXES:
        parts.append(f"## {AXIS_LABEL[axis]}")
        parts.append("")
        for e in catalog["by_axis"][axis]:
            parts.append(f"- [{e['name']}]({entry_url(axis, e['id'])}) - {e.get('one_liner', '')}")
        parts.append("")
    return _page("Reference", "Every entry across the four axes.", "\n".join(parts))


def render_diff_pair_index(pairs: list[dict]) -> str:
    by_axis: dict[str, list[dict]] = {}
    for p in pairs:
        by_axis.setdefault(p["axis_varied"], []).append(p)
    parts = []
    for axis in sorted(by_axis):
        parts.append(f"## Varying {axis}")
        parts.append("")
        for p in by_axis[axis]:
            parts.append(
                f"- [{p['entry_a']} vs {p['entry_b']}]"
                f"({BASE}/examples/diff-pairs/{p['diff_pair_id']}/) - {p['topic_label']}"
            )
        parts.append("")
    return _page("Diff-pairs", "Side-by-side single-axis contrasts.", "\n".join(parts))


def render_recipe_index(catalog: dict) -> str:
    parts = []
    for slug in list_recipes():
        parts.append(f"- [{slug}]({BASE}/recipes/{slug}/)")
    return _page("Recipes", "Curated four-axis compositions.", "\n".join(parts))


def render_template_index(catalog: dict) -> str:
    parts = []
    for e in catalog["by_axis"]["format"]:
        if e.get("canonical_template"):
            parts.append(f"- [{e['name']}]({BASE}/templates/{e['id']}/)")
    return _page("Templates", "Canonical format templates.", "\n".join(parts))


def render_examples_topic_index(catalog: dict, topic: str) -> str:
    parts = [f"Vertical-slice examples for this topic, one per entry. "
             f"Each is also embedded on its entry's reference page.", ""]
    return _page(topic, f"Examples for the {topic} anchor topic.", "\n".join(parts))


def _write(out_root: Path, rel: str, content: str) -> None:
    path = out_root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def generate(out_root: Path) -> int:
    catalog = load_catalog()
    pairs = load_diff_pairs()
    n = 0

    # Entry pages (.mdx because they import components / use <Tabs>)
    for axis in AXES:
        for entry in catalog["by_axis"][axis]:
            rel = f"reference/{AXIS_DIR[axis]}/{entry['id']}.mdx"
            _write(out_root, rel, render_entry_page(catalog, pairs, entry))
            n += 1
    _write(out_root, "reference/index.md", render_reference_index(catalog))

    # Diff-pair pages (.mdx, import DiffPair)
    for dp in pairs:
        _write(out_root, f"examples/diff-pairs/{dp['diff_pair_id']}.mdx",
               render_diff_pair_page(catalog, dp))
        n += 1
    _write(out_root, "examples/diff-pairs/index.md", render_diff_pair_index(pairs))

    # Example topic index pages
    for topic in TOPICS:
        _write(out_root, f"examples/{topic}/index.md",
               render_examples_topic_index(catalog, topic))

    # Recipes
    for slug in list_recipes():
        _write(out_root, f"recipes/{slug}.md", render_recipe_page(catalog, slug))
        n += 1
    _write(out_root, "recipes/index.md", render_recipe_index(catalog))

    # Templates
    for e in catalog["by_axis"]["format"]:
        if e.get("canonical_template"):
            _write(out_root, f"templates/{e['id']}.md", render_template_page(e))
            n += 1
    _write(out_root, "templates/index.md", render_template_index(catalog))

    return n


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(DOCS), help="output docs root")
    ap.add_argument("--lint", action="store_true", help="report source-prose fidelity warnings and exit")
    args = ap.parse_args()
    if args.lint:
        catalog = load_catalog()
        total = 0
        for axis in AXES:
            for e in catalog["by_axis"][axis]:
                for w in fidelity_warnings(e.get("_body", "")):
                    print(f"taxonomy/{AXIS_DIR[axis]}/{e['id']}/ENTRY.md: {w}")
                    total += 1
        for md in sorted((EXAMPLES / "vertical-slices").rglob("*.md")):
            _, body = load_markdown(md.read_text(encoding="utf-8"))
            for w in fidelity_warnings(body):
                print(f"{md.relative_to(REPO_ROOT)}: {w}")
                total += 1
        print(f"[lint] {total} fidelity warning(s)")
        return 0
    out_root = Path(args.out)
    count = generate(out_root)
    print(f"[OK] generated {count} catalog pages into {out_root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
