#!/usr/bin/env python3
"""Generate Starlight docs pages from the writing-style-library catalog.

Reads taxonomy/ and examples/ (with PyYAML, NOT the repo's hand-rolled parser)
and writes committed Markdown/MDX into docs/ where Starlight's autogenerate
sidebar renders it. Emits Starlight-correct slug links in-generator; there is
NO post-build link rewriter (see ADR 0011 and the design spec section 5.5).

Usage:
    python scripts/generate_site_pages.py            # write into docs/
    python scripts/generate_site_pages.py --out DIR  # write into DIR (used by the freshness check)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
TAXONOMY = REPO_ROOT / "taxonomy"
EXAMPLES = REPO_ROOT / "examples"
DOCS = REPO_ROOT / "docs"

AXES = ["voice", "tone", "style", "format"]
AXIS_DIR = {"voice": "voices", "tone": "tones", "style": "styles", "format": "formats"}
TOPICS = ["async-standups", "morning-routine", "service-database-choice"]

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/generate_site_pages.py - do not edit by hand. "
    "Edit the source under taxonomy/ or examples/ and regenerate. -->"
)

_FM_SPLIT = re.compile(r"(?ms)\A---[ \t]*\n(.*?)\n---[ \t]*\n?(.*)\Z")


def load_markdown(raw: str) -> tuple[dict, str]:
    """Split a frontmatter markdown string into (frontmatter dict, body).

    Normalizes CRLF/CR to LF first so the result does not depend on how the
    caller obtained the string (the repo ships CRLF files).
    """
    raw = raw.replace("\r\n", "\n").replace("\r", "\n")
    m = _FM_SPLIT.match(raw)
    if not m:
        raise ValueError("no frontmatter block found")
    fm = yaml.safe_load(m.group(1)) or {}
    return fm, m.group(2)


def read_entry(axis: str, entry_dir: Path) -> dict:
    fm, body = load_markdown((entry_dir / "ENTRY.md").read_text(encoding="utf-8"))
    fm["_axis"] = axis
    fm["_body"] = body
    return fm


BASE = "/writing-style-library"


def entry_url(axis: str, entry_id: str) -> str:
    """Starlight slug URL for an entry's reference page (trailing slash)."""
    return f"{BASE}/reference/{AXIS_DIR[axis]}/{entry_id}/"


def entry_link(catalog: dict, entry_id: str) -> str:
    """Markdown link to an entry by id, using its display name. Falls back to the id."""
    entry = catalog["by_id"].get(entry_id)
    if not entry:
        return f"`{entry_id}`"
    return f"[{entry['name']}]({entry_url(entry['_axis'], entry_id)})"


def load_catalog() -> dict:
    by_id: dict[str, dict] = {}
    by_axis: dict[str, list[dict]] = {a: [] for a in AXES}
    for axis in AXES:
        axis_path = TAXONOMY / AXIS_DIR[axis]
        for entry_dir in sorted(axis_path.iterdir()):
            if not entry_dir.is_dir():
                continue
            entry = read_entry(axis, entry_dir)
            by_id[entry["id"]] = entry
            by_axis[axis].append(entry)
    return {"by_id": by_id, "by_axis": by_axis}
